language: c++
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.7
    - kalakris-cmake
    packages:
    - llvm-3.7
    - llvm-3.7-runtime
    - libllvm3.7
    - libstdc++6
    - cmake
    - build-essential
install: bash -e .travis-ci.sh
cache:
  directories:
  - $HOME/cmake-3.2.2
  - $HOME/llvm-3.7.0
  - $HOME/llvm-3.7.0.src
  
script: cmake -f CMakeLists.txt